pipeline {
  agent any
  tools {
    maven 'Maven 3.8' 
  }
  stages {
    stage ('Build') {
      steps {
	      	dir('AngularSpringWebservice') {
	        	sh 'mvn clean package -DskipTests=true' 
	      		}	
      		}
    	}
	}
  }